/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppBackground {
    }
    interface AppCart {
    }
    interface AppFooter {
    }
    interface AppHeader {
    }
    interface AppHome {
    }
    interface AppList {
    }
    interface AppLogin {
    }
    interface AppProfile {
        "name": string;
    }
    interface AppRoot {
    }
}
declare global {
    interface HTMLAppBackgroundElement extends Components.AppBackground, HTMLStencilElement {
    }
    var HTMLAppBackgroundElement: {
        prototype: HTMLAppBackgroundElement;
        new (): HTMLAppBackgroundElement;
    };
    interface HTMLAppCartElement extends Components.AppCart, HTMLStencilElement {
    }
    var HTMLAppCartElement: {
        prototype: HTMLAppCartElement;
        new (): HTMLAppCartElement;
    };
    interface HTMLAppFooterElement extends Components.AppFooter, HTMLStencilElement {
    }
    var HTMLAppFooterElement: {
        prototype: HTMLAppFooterElement;
        new (): HTMLAppFooterElement;
    };
    interface HTMLAppHeaderElement extends Components.AppHeader, HTMLStencilElement {
    }
    var HTMLAppHeaderElement: {
        prototype: HTMLAppHeaderElement;
        new (): HTMLAppHeaderElement;
    };
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppListElement extends Components.AppList, HTMLStencilElement {
    }
    var HTMLAppListElement: {
        prototype: HTMLAppListElement;
        new (): HTMLAppListElement;
    };
    interface HTMLAppLoginElement extends Components.AppLogin, HTMLStencilElement {
    }
    var HTMLAppLoginElement: {
        prototype: HTMLAppLoginElement;
        new (): HTMLAppLoginElement;
    };
    interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {
    }
    var HTMLAppProfileElement: {
        prototype: HTMLAppProfileElement;
        new (): HTMLAppProfileElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLElementTagNameMap {
        "app-background": HTMLAppBackgroundElement;
        "app-cart": HTMLAppCartElement;
        "app-footer": HTMLAppFooterElement;
        "app-header": HTMLAppHeaderElement;
        "app-home": HTMLAppHomeElement;
        "app-list": HTMLAppListElement;
        "app-login": HTMLAppLoginElement;
        "app-profile": HTMLAppProfileElement;
        "app-root": HTMLAppRootElement;
    }
}
declare namespace LocalJSX {
    interface AppBackground {
    }
    interface AppCart {
    }
    interface AppFooter {
    }
    interface AppHeader {
    }
    interface AppHome {
    }
    interface AppList {
    }
    interface AppLogin {
    }
    interface AppProfile {
        "name"?: string;
    }
    interface AppRoot {
    }
    interface IntrinsicElements {
        "app-background": AppBackground;
        "app-cart": AppCart;
        "app-footer": AppFooter;
        "app-header": AppHeader;
        "app-home": AppHome;
        "app-list": AppList;
        "app-login": AppLogin;
        "app-profile": AppProfile;
        "app-root": AppRoot;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-background": LocalJSX.AppBackground & JSXBase.HTMLAttributes<HTMLAppBackgroundElement>;
            "app-cart": LocalJSX.AppCart & JSXBase.HTMLAttributes<HTMLAppCartElement>;
            "app-footer": LocalJSX.AppFooter & JSXBase.HTMLAttributes<HTMLAppFooterElement>;
            "app-header": LocalJSX.AppHeader & JSXBase.HTMLAttributes<HTMLAppHeaderElement>;
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-list": LocalJSX.AppList & JSXBase.HTMLAttributes<HTMLAppListElement>;
            "app-login": LocalJSX.AppLogin & JSXBase.HTMLAttributes<HTMLAppLoginElement>;
            "app-profile": LocalJSX.AppProfile & JSXBase.HTMLAttributes<HTMLAppProfileElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
        }
    }
}
